"":
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  joint_group_position_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
          - base_lf1
          - lf1_lf2
          - lf2_lf3
          - base_rf1
          - rf1_rf2
          - rf2_rf3
          - base_lb1
          - lb1_lb2
          - lb2_lb3
          - base_rb1
          - rb1_rb2
          - rb2_rb3

      gains:
        base_lf1 : {p: 5, d: 0, i: 1}
        lf1_lf2 : {p: 5, d: 0, i: 1}
        lf2_lf3 : {p: 5, d: 0, i: 1}
        base_rf1 : {p: 5, d: 0, i: 1}
        rf1_rf2 : {p: 5, d: 0, i: 1}
        rf2_rf3 : {p: 5, d: 0, i: 1}
        base_lb1 : {p: 5, d: 0, i: 1}
        lb1_lb2 : {p: 5, d: 0, i: 1}
        lb2_lb3 : {p: 5, d: 0, i: 1}
        base_rb1 : {p: 5, d: 0, i: 1}
        rb1_rb2 : {p: 5, d: 0, i: 1}
        rb2_rb3 : {p: 5, d: 0, i: 1}
